/* F1 Vaguepost Generator — content banks.
 * All fictional. Mix-and-match template fuel for maximum silly-season chaos. */

const DATA = {
  // Loosely current-era grid + legends people still tweet about.
  drivers: [
    "Verstappen", "Norris", "Leclerc", "Hamilton", "Russell", "Piastri",
    "Sainz", "Alonso", "Gasly", "Ocon", "Stroll", "Albon", "Hulkenberg",
    "Tsunoda", "Bottas", "Bearman", "Antonelli", "Colapinto", "Lawson",
    "Ricciardo", "Perez", "Vettel", "Schumacher"
  ],

  teams: [
    "Red Bull", "Ferrari", "Mercedes", "McLaren", "Aston Martin",
    "Alpine", "Williams", "Haas", "RB", "Sauber", "Audi",
    "Cadillac", "a mystery American outfit"
  ],

  nationalities: [
    "British", "Dutch", "Spanish", "Monegasque", "Australian", "French",
    "German", "Italian", "Mexican", "Danish", "Thai", "Japanese", "Finnish"
  ],

  grandsPrix: [
    "Monaco", "Silverstone", "Monza", "Spa", "Suzuka", "Bahrain",
    "Jeddah", "Miami", "Vegas", "Singapore", "Austin", "Interlagos",
    "Zandvoort", "the Hungaroring", "Baku", "Imola", "Qatar", "Abu Dhabi"
  ],

  journalists: [
    "a very reliable source", "someone close to the situation",
    "a senior paddock figure", "my guy in the paddock",
    "multiple sources", "a person familiar with the talks",
    "an engineer who shall remain nameless", "someone who was in the room"
  ],

  sponsors: [
    "a major crypto brand", "an energy drink you've never heard of",
    "a Middle Eastern airline", "a luxury watch house",
    "a fashion label", "a sports betting giant", "a Saudi tourism board"
  ],

  bodyParts: ["the front wing", "the floor", "the rear end", "the power unit",
    "the sidepods", "the diffuser", "the DRS", "the brake ducts"],

  vibes: ["not happy", "seething", "very quiet", "surprisingly relaxed",
    "up to something", "cooking", "cooked", "locked in", "unwell", "back",
    "finished", "fuming", "glowing", "shaking", "done", "eating good",
    "in his bag", "on borrowed time"],

  timeframes: ["within days", "before the summer break", "by winter testing",
    "sooner than you think", "before the next race", "by the end of the month",
    "any day now", "before {gp}", "in the coming weeks", "by lights out in {gp}"],

  cryptic: ["👀", "🍿", "🤐", "🤔", "😏", "🫡", "📌", "🚨", "🤫", "🔥", "🧩", "⏳"],

  // Fake ITK account personas for the tweet card.
  personas: [
    { name: "F1 Paddock Insider", handle: "f1_paddock_ITK", emoji: "🏎️" },
    { name: "Silly Season HQ", handle: "SillySeasonHQ", emoji: "🎪" },
    { name: "Box Box Box", handle: "boxboxbox_f1", emoji: "📦" },
    { name: "Grid Whispers", handle: "gridwhispers", emoji: "🤫" },
    { name: "The Undercut", handle: "TheUndercut_", emoji: "✂️" },
    { name: "DRS Detective", handle: "drs_detective", emoji: "🕵️" },
    { name: "Paddock Club Leaks", handle: "paddockleaks", emoji: "🔓" },
    { name: "Tenth Hunter", handle: "tenthhunter", emoji: "⏱️" },
    { name: "Formula Rumours", handle: "formularumours", emoji: "🌀" },
    { name: "Marbles Off Line", handle: "marbles_offline", emoji: "⚫" }
  ],

  // ---- Templates. {tokens} resolved by app.js against the banks above. ----

  rumours: [
    "🚨 BREAKING: {driver} to {team} for {year}. {journalist} tells me talks are 'advanced'.",
    "Hearing {driver}'s management were spotted at {team}'s factory this week 👀",
    "{team} reportedly bringing a major upgrade to {gp} — could be worth {tenths} of a second.",
    "{driver} and {driver2} relationship said to be 'at breaking point' according to {journalist}.",
    "Told {driver} has a performance clause that activates if they're behind {driver2} at {gp}. Interesting.",
    "🚨 {team} in advanced talks with {sponsor} for a title sponsorship worth a reported ${money}M.",
    "{driver} has NOT signed for {year} yet. Let that sink in.",
    "Whispers that {team} have already locked in {driver} for {year}. You didn't hear it from me.",
    "{journalist} says {team} are 'seriously concerned' about {bodyPart} ahead of {gp}.",
    "{driver} reportedly testing an old-spec chassis in the sim. Make of that what you will.",
    "Contract of {driver} said to contain a release clause tied to constructors' position. 🍿",
    "🚨 {team} could run a special livery at {gp}. Big announcement expected.",
    "Hearing {driver} turned down {team}. Yes, really.",
    "{team} engineers reportedly unhappy after {gp}. {journalist} says it's 'tense' in there.",
    "Sources: {driver} to test for {team} in the post-season young driver test. He's {age}, by the way.",
    "{driver}'s race engineer could be on the move to {team}. These things matter.",
    "Told the {team} garage went very quiet after {driver} said something on the radio at {gp}.",
    "🚨 {journalist} tells me {driver} to {team} could be announced {timeframe}. {emoji}",
    "{team} have reportedly triggered the option year on {driver}'s deal. It's happening.",
    "Hearing {driver} has a handshake agreement with {team}. Nothing on paper yet. {emoji}",
    "{driver} to {team} would mean {driver2} is out. Do the math.",
    "{team} said to be lining up {driver} as a direct replacement {timeframe}.",
    "Whispers of a {sponsor} deal walking away from {team} over results. Ouch.",
    "{team} reportedly protesting {bodyPart} on a rival car after {gp}. This could get messy.",
    "Told {driver} skipped the {team} debrief at {gp}. That never happens.",
    "{driver}'s data engineer reportedly seen leaving the {team} hospitality. 🧩",
    "Sources: {team} to bring a B-spec car to {gp}. Worth up to {tenths}s a lap.",
    "{driver} contract talks with {team} said to have 'stalled completely'. {emoji}",
    "Hearing the {team} board wants {driver} regardless of cost. {timeframe}, apparently.",
    "{driver} reportedly unhappy with {bodyPart} balance and it's 'affecting the mood'. {emoji}",
    "🚨 {driver} has been released from his {team} contract early. Announcement {timeframe}.",
    "Told {driver} and {driver2} have not spoken since {gp}. Teammates, by the way.",
    "{team} scouts reportedly at a karting round watching a {age}-year-old. The pipeline never sleeps.",
    "{journalist} says {team} are quietly shopping for a new {bodyPart} concept for {year}.",
    "{driver} said to be learning {nationality}... make of that what you will. {emoji}",
    "Rumour doing the rounds that {driver}'s {year} seat depends on a single result at {gp}.",
    "{team} reportedly furious about a leak from inside the garage at {gp}. Heads may roll.",
    "Hearing {driver}'s camp have gone cold on {team}. Something changed {timeframe}.",
    "{team} to reportedly announce a driver line-up shake-up {timeframe}. Buckle up. {emoji}",
    "Told a {sponsor} exec was seen in the {team} motorhome for two hours at {gp}. 🤔",
    "{driver} clocked the fastest {team} sim time in months this week. Coincidence? {emoji}",
    "{journalist}: '{driver} to {team} is done, it's just about when.' {timeframe}, I'm told.",
    "{team} reportedly weighing a full {bodyPart} redesign after a bad {gp}. Costly.",
    "Whispers {driver} could sit out the rest of the year. His seat? Already being circled. {emoji}",
    // ---- expanded batch ----
    "🚨 BREAKING: {driver} to {team} for {year}. {journalist} tells me talks are 'advanced' 👀",
    "Hearing {driver} has a release clause worth {money}. Silly season just got expensive.",
    "Told {driver}'s camp went ICE cold on {team} after {gp}. Something happened in that room 🤐",
    "Sources say {team} triggered {driver}'s option {timeframe}. Nobody's confirming. Nobody's denying.",
    "{driver} spotted at {team} HQ. In {nationality}. On his day off. Draw your own conclusions {emoji}",
    "Hearing {driver} turned down {team}. Yes, really. For {money} less.",
    "🚨 {driver} management meeting scheduled {timeframe}. {sponsor} reportedly 'not happy'.",
    "Whisper in the paddock: {driver} and {driver2} could swap seats for {year}. I've said too much.",
    "{journalist} hearing {driver}'s deal with {team} collapsed over {money}. Down to the wire.",
    "Told the {driver} to {team} contract is 'done in principle'. In principle is doing a lot of work here.",
    "{driver} camp gone quiet. Too quiet. {timeframe} could be BIG 🍿",
    "Hearing {team} want {driver} so badly they'd release {driver2} same day. Ruthless.",
    "BREAKING: {driver} signs {team} extension through {year}. {money} a year, I'm told 🤑",
    "{driver}'s {nationality} backers pushing hard for the {team} seat. Politics, baby.",
    "Sources: {driver} has a performance clause — if he's within {tenths} of {driver2}, the seat's his.",
    "Told {driver} rejected {team}'s first offer by {money}. Second offer landing {timeframe}.",
    "{driver} to {team}. {driver2} to nowhere. That's the whisper and I'm sticking to it.",
    "Hearing {sponsor} is quietly funding a {driver} to {team} move. Follow the money 👀",
    "{journalist} says {driver}'s {team} camp is 'radioactive' right now. Read into that what you will.",
    "🚨 {driver} contract talks PAUSED. Not dead. Paused. There's a difference {emoji}",
    "Whisper: {team} offered {driver} the seat AND {driver2}'s garage number. Cold-blooded.",
    "Told {driver} won't sign anything until after {gp}. Wants to see the {tenths} first.",
    "{driver} agent seen leaving {team} motorhome looking {vibe}. That's all I've got. That's enough.",
    "Hearing {driver}'s people want {money} and a {sponsor} clause. {team} said 'let us think'.",
    "BREAKING: {driver} has {timeframe} to accept {team}. After that? {driver2} gets the call.",
    "{age} years old and {driver} is holding the whole grid hostage. Respect the game 🍿",
    "Sources say {driver} to {team} is '90% done'. The other 10% is {money}.",
    "Told {driver} and {team} shook hands {timeframe}. No paper yet. Handshakes break, folks.",
    "{driver}'s {nationality} sponsors reportedly threatening to walk if the {team} deal dies 🤐",
    "Hearing {driver2} found out about the {driver} to {team} talks from Twitter. Ouch.",
    "🚨 {driver} option deadline is {timeframe}. {team} STILL haven't decided. Chaos incoming.",
    "Whisper: {driver} would take a {money} pay cut just to get out of {team}. He's DONE.",
    "{journalist} tells me {driver} is 'as good as gone' from {team}. Buckle up.",
    "Told there's a secret {driver} to {team} clause that activates if they finish ahead by {tenths}.",
    "{driver} camp feeling {vibe} about {year}. {team} might already know something we don't.",
    "Hearing {driver} met {team} bosses in {nationality}. Dinner ran 4 hours. That's not a casual dinner {emoji}",
    "BREAKING: {team} preparing a {money} offer to prise {driver} away {timeframe}.",
    "{driver} to {team} rumours getting louder. {driver2} unusually quiet. Coincidence? 👀",
    "Sources: {driver}'s contract has a {gp} exit clause nobody knew about. Sneaky sneaky.",
    "Told {driver} turned {vibe} when {team} was mentioned. Whole camp did. Interesting.",
    "{driver} reportedly wants {driver2}'s seat SPECIFICALLY. This is personal now 🍿",
    "Hearing {sponsor} will only stay if {driver} signs {team} by {year}. Ticking clock.",
    "🚨 {driver} extension at {team} 'hits a snag'. The snag is worth about {money}.",
    "Whisper: {team} lining up {driver} as a straight swap for {driver2}. {timeframe} decides it.",
    "{journalist} says {driver}'s {nationality} management is playing three teams at once. Genius or greedy?",
    "Told {driver} won't move for less than {money}. At {age}, he's earned the leverage.",
    "{driver} to {team} would break a {tenths} deadlock in that garage instantly. Bosses know it.",
    "Hearing the {driver} deal is signed but embargoed until after {gp}. You didn't hear it from me 🤐",
    "BREAKING: {driver} camp and {team} 'back at the table' {timeframe}. This one's not over 🍿",
    "{team} reportedly bringing a major upgrade to {gp} — insiders say it's worth {tenths}s a lap 👀",
    "Told {team} are quietly worried about {bodyPart} overheating in the {gp} sun 🔧",
    "Hearing the new {bodyPart} concept on the {team} didn't pass FIA load tests {timeframe} 🧩",
    "Whispers in the paddock: {team} found {tenths}s in the wind tunnel that isn't showing up on track.",
    "{team} said to be lodging a protest against {team2} over their {bodyPart} at {gp}.",
    "Told {driver} was furious about porpoising down the main straight at {gp} 👀",
    "Sources: {team} correlation issues between CFD and wind tunnel costing them {tenths}s per lap.",
    "Hearing {team} will run a stripped-back {bodyPart} at {gp} to save on tyre wear.",
    "{journalist}: {team} have a new engine mode worth {tenths}s but only good for {timeframe}.",
    "Paddock talk: {team} pit crew practising nights after a {money}-second stop cost {driver} at {gp} 🔧",
    "Told {team}'s sim numbers for {gp} are 'unbelievable' — {tenths}s clear of the field 👀",
    "Sources say {driver} reported the {bodyPart} 'feels alive' over kerbs — engineers not happy.",
    "Hearing the FIA sent {team} a technical directive about their {bodyPart} {timeframe} 🧩",
    "{team} reportedly binning their {year} {bodyPart} concept entirely after {gp}.",
    "Whispers: {team} carrying {money}kg of extra ballast to hide their real pace 👀",
    "Told {team} are chasing a flexi-{bodyPart} solution that {journalist} calls 'borderline legal'.",
    "Sources: {driver}'s tyres went off a cliff {tenths}s faster than {team} expected at {gp}.",
    "Hearing {team} tunnel booked solid all {timeframe} chasing a fix for {bodyPart} 🔧",
    "{journalist} reports {team} may protest the results of {gp} over a {bodyPart} irregularity.",
    "Told {team} discovered a reliability gremlin in {bodyPart} that could cost them {gp} 👀",
    "Sources: {team} bringing three upgrade packages to {gp}, total value {tenths}s a lap 🧩",
    "Paddock rumour: {driver} lapped {tenths}s under the sim target in {timeframe} of night running.",
    "Hearing {team} de-rated their engine {timeframe} to protect {bodyPart} — worth {tenths}s lost.",
    "{team} said to be copying {team2}'s {bodyPart} concept for {gp}. {journalist} 'stunned'.",
    "Told {team} found porpoising returned the moment they added the new {bodyPart} 🔧",
    "Sources: {driver} and {driver2} split on setup — one wants softer {bodyPart}, one stiffer.",
    "Whispers: {team}'s {gp} upgrade slipped past scrutineering with the {bodyPart} 'just' legal 👀",
    "Hearing {team} spent {money} million on a {bodyPart} redesign that {journalist} says 'does nothing'.",
    "{journalist}: {team} tyre-wear model is {tenths}s off reality and no one knows why.",
    "Told {team} are sandbagging in testing — real pace {tenths}s better than the timesheets 👀",
    "Sources: {team} to introduce a revised {bodyPart} at {gp} after failing a deflection test.",
    "Hearing {driver}'s brakes were {tenths}s away from failure at {gp} — {team} kept it quiet 🔧",
    "Paddock talk: {team}'s new floor edge is so aggressive the FIA want it gone {timeframe} 🧩",
    "Told {team} ran a secret aero rake day and found {tenths}s in {bodyPart} downforce 👀",
    "Sources: {team2} lodging a right-of-review over {team}'s {bodyPart} at {gp}.",
    "Hearing {team} may skip the {gp} upgrade entirely — {bodyPart} 'not correlating' 🔧",
    "{journalist} says {team} pit stop software glitched, adding {money} seconds for {driver}.",
    "Told {team} are worried their {bodyPart} won't survive the bumps at {gp} 👀",
    "Sources: {team} chasing {tenths}s with a new engine mode nicknamed 'the {vibe}' internally 🧩",
    "Whispers: {driver} demanded {team} revert to the old {bodyPart} spec after {gp}.",
    "Hearing {team} cooling problems mean they'll run open bodywork and lose {tenths}s at {gp} 🔧",
    "{journalist}: {team}'s wind tunnel is 'lying to them' — {tenths}s that vanishes on track.",
    "Told {team} found a {bodyPart} crack {timeframe} — parts being flown in for {gp} 👀",
    "Sources: {team} to trial an experimental {bodyPart} in FP1 at {gp}, could be worth {tenths}s.",
    "Hearing {driver} lost {tenths}s per lap because the {bodyPart} was set up for {driver2} 🔧",
    "Paddock rumour: {team}'s {gp} spec is a full {money}-million rethink of the {bodyPart} 🧩",
    "Told the FIA are watching {team}'s {bodyPart} flex on the straights at {gp} very closely 👀",
    "Sources: {team} scrapping their {year} concept mid-season, {tenths}s behind and out of tunnel time 🔧",
    "{driver} and {driver2} 'haven't made eye contact' since {gp}, per {journalist}. Teammates. 🍿",
    "Told the {team} garage went dead silent after {driver} climbed out at {gp}. 🤐",
    "{journalist}: {driver} feels the {team} board has 'gone cold' on him since {year}.",
    "Hearing {driver} and {driver2} now have separate engineering debriefs. Coincidence? 👀",
    "{team} lead strategist reportedly {vibe} and 'weighing his options' after {gp}.",
    "{driver} said to be {vibe} that {driver2} got the upgrade first. It's about {tenths} of a second, apparently.",
    "Radio fallout at {gp}: {driver} told his engineer to 'never say that again'. Things are tense. 🤐",
    "{journalist} hears {driver} skipped the {team} team dinner at {gp}. Draw your own conclusions.",
    "{team} principal 'under serious pressure' from the board after another {gp} they'd rather forget.",
    "Told {driver} and {driver2} were kept in separate rooms during the {team} debrief. 👀",
    "{sponsor} reportedly '{vibe}' about the {team} drama and asking questions behind closed doors. {money} is a lot to be quiet about.",
    "Whispers that a senior {team} engineer is packing his {bodyPart} and leaving {timeframe}.",
    "{driver} unfollowed {team} on socials {timeframe}. Nothing? Or everything? 👀",
    "{journalist}: '{driver} and {driver2} genuinely can't stand each other now.' You heard it here.",
    "The {team} garage mood after {gp} described to me as 'a funeral, but quieter'. 🤐",
    "Hearing the {team} board had a {vibe} emergency meeting about {driver}'s future {timeframe}.",
    "{driver} reportedly refused to do the joint photo with {driver2} at {gp}. Told it got awkward.",
    "{team} press officer has gone fully silent on {driver} questions. Media blackout vibes. 🤐",
    "Told {driver} feels 'thrown under the bus' by {team} after what {journalist} wrote post-{gp}.",
    "{driver2} said to be {vibe} that the {nationality} media keep comparing him to {driver}.",
    "Word is {sponsor} threatened to pull {money} unless the {team} feud cools down {timeframe}.",
    "{team} engineers 'quietly furious' after {driver} publicly blamed the car at {gp}.",
    "Hearing {driver} and {driver2} had 'words' in the {team} hospitality after {gp}. 🍿",
    "{journalist} says {driver}'s manager and the {team} principal 'aren't speaking' right now.",
    "Told the {team} data leaked from the garage at {gp} and everyone's pointing at everyone. 👀",
    "{driver} reportedly asked the team NOT to give {driver2} the same {bodyPart}-tightening setup. Petty? Maybe.",
    "{team} board 'split down the middle' on whether to keep {driver} for {year}, per {journalist}.",
    "The {vibe} silence between {driver} and {driver2} on the drivers' parade at {gp} said it all. 🍿",
    "Hearing a {team} mechanic quit on the spot after {gp}. Just walked. 👀",
    "{driver} deleted every {team} post from {year} off his grid. He's {vibe}, clearly.",
    "{journalist}: '{team} is a powder keg right now and {gp} lit the fuse.'",
    "Told {sponsor} execs left the {team} garage at {gp} looking absolutely {vibe}. 🤐",
    "{driver} and {driver2} reportedly demanded separate hotels {timeframe}. It's that deep now.",
    "A {nationality} outlet claims {driver} called the {team} principal 'a liar' behind closed doors.",
    "{team} technical director said to be {vibe} and eyeing an exit after being overruled on the {year} car.",
    "Hearing {driver} hasn't replied to the {team} group chat since {gp}. Left on read, the lot of them. 🍿",
    "{journalist} reckons {driver2} was promised the {age} status of team leader and it never came. He's fuming.",
    "The {team} radio went suspiciously quiet on {driver} for the last ten laps at {gp}. 👀",
    "Told {driver} stormed past {journalist} without a word after {gp}. Media freeze is on. 🤐",
    "{team} board reportedly {vibe} about a {money} sponsor gap and it's getting political fast.",
    "Word from the paddock: {driver} and {driver2} now travel with separate PR teams. Cold war. ❄️",
    "{team} insiders say the {driver} vs {driver2} thing is 'the worst they've ever seen' {emoji}",
    "Hearing {driver}'s race engineer requested a swap to {driver2}'s {bodyPart} of the garage. Ouch. 👀",
    "{journalist}: a key {team} sponsor meeting {timeframe} 'did not go well'. Understatement of {year}.",
    "Told {driver} left the {gp} debrief early and {vibe}. Slammed a door, allegedly. 🤐",
    "{team} principal dodged every {driver} question in the presser. That's not nothing. 👀",
    "Whispers that {driver2} bad-mouthed {driver} to {sponsor} at a {nationality} event. It got back to him. 🍿",
    "Hearing three {team} staff have handed notice in since {gp}. Something's rotten in there.",
    "{driver} reportedly told the {team} board it's 'him or {driver2}' for {year}. Bold. 🍿",
    "The {team} garage 'hasn't been the same' since {driver} and {driver2} fell out at {gp}, says {journalist}. 🤐"
  ],

  // Vagueposts scored by vagueness (1 = names names, 5 = pure cryptic void).
  // The vagueness slider filters to a level. Keep every level stocked.
  vagueposts: [
    // --- 1: barely subtle (basically a rumour with a wink) ---
    { text: "{driver} at {team}. that's the tweet. work it out. 👀", vague: 1 },
    { text: "keep an eye on the {team} garage at {gp}. that's all. 👀", vague: 1 },
    { text: "{driver} and {team}. remember where you heard it. 📌", vague: 1 },
    { text: "{driver} to {team}. i won't say more than that. 🤐", vague: 1 },
    { text: "{driver}. {team}. {timeframe}. that's the whole tweet. {emoji}", vague: 1 },
    { text: "so {driver} is testing at {team} now? interesting. {emoji}", vague: 1 },
    { text: "write {driver} to {team} down. check back {timeframe}. 📌", vague: 1 },
    { text: "the {driver} to {team} people are about to eat VERY good. {emoji}", vague: 1 },
    { text: "{team} fans, check on your {driver} rumours {timeframe}. 👀", vague: 1 },

    // --- 2: names a name, withholds the point ---
    { text: "not everything is as it seems in {team} right now.", vague: 2 },
    { text: "some of you are going to look very silly by {gp}. 🤡", vague: 2 },
    { text: "so THAT'S why {driver} was smiling. 😏", vague: 2 },
    { text: "the {vibe} energy from {team} today was very telling.", vague: 2 },
    { text: "funny how quiet it's gone since {gp}, isn't it?", vague: 2 },
    { text: "{driver} is {vibe}. and i think that says it all.", vague: 2 },
    { text: "{team} know exactly what they're doing. or do they. 🤔", vague: 2 },
    { text: "the real story of {gp} hasn't been told yet.", vague: 2 },
    { text: "{driver} is {vibe} and the {team} garage knows exactly why. {emoji}", vague: 2 },
    { text: "whatever {driver} just did, {team} won't forget it. {emoji}", vague: 2 },
    { text: "the {team} debrief after {gp} must have been something else. 🍿", vague: 2 },
    { text: "ask {driver} about {gp}. go on. ask. 😏", vague: 2 },
    { text: "there's a reason {driver} went so quiet after {gp}.", vague: 2 },
    { text: "{team} are one bad {gp} away from something dramatic. {emoji}", vague: 2 },
    { text: "keep {driver}'s name in your drafts. you'll need it {timeframe}. 📌", vague: 2 },
    { text: "{driver} smiling like that after {gp}? not normal. {emoji}", vague: 2 },

    // --- 3: a shape, no name ---
    { text: "someone in that garage isn't happy 👀", vague: 3 },
    { text: "a certain {nationality} driver has some explaining to do.", vague: 3 },
    { text: "no notes. no context. just vibes. {driver} 👀", vague: 3 },
    { text: "a certain garage was very quiet today. you can guess which. 👀", vague: 3 },
    { text: "someone made a phone call they'll regret. 📞", vague: 3 },
    { text: "a certain driver is {vibe}. that's all you need to know. {emoji}", vague: 3 },
    { text: "a certain {nationality} driver knows exactly what he did. {emoji}", vague: 3 },
    { text: "one of the big teams is about to have a very bad week. {emoji}", vague: 3 },
    { text: "someone in that paddock is lying through their teeth right now.", vague: 3 },
    { text: "a driver you love is {vibe} behind closed doors. 🧩", vague: 3 },
    { text: "two garages. one secret. {timeframe}. {emoji}", vague: 3 },
    { text: "a certain someone did NOT enjoy {gp}. and it shows. 👀", vague: 3 },

    // --- 4: gesturing at nothing in particular ---
    { text: "certain people need to have a look in the mirror.", vague: 4 },
    { text: "the paddock is talking. that's all i'll say.", vague: 4 },
    { text: "interesting few days ahead. keep your notifications on.", vague: 4 },
    { text: "the timing of all this... no coincidence.", vague: 4 },
    { text: "certain garages should be careful what they wish for.", vague: 4 },
    { text: "big if true. and it's true. 👀", vague: 4 },
    { text: "we are NOT ready for what's coming.", vague: 4 },
    { text: "somebody's phone is about to blow up. it's not mine. it's theirs.", vague: 4 },
    { text: "i've said too much. deleting later. 🫡", vague: 4 },
    { text: "some of you are about to owe me an apology. {timeframe}. {emoji}", vague: 4 },
    { text: "there is a storm coming and only a few of us can feel it. {emoji}", vague: 4 },
    { text: "everyone's looking in the wrong direction right now. good. {emoji}", vague: 4 },
    { text: "the quiet ones in the paddock are the ones to watch. 🤫", vague: 4 },
    { text: "something happened this week that changes everything. {timeframe} you'll see.", vague: 4 },
    { text: "trust the process. or don't. i know what i know. {emoji}", vague: 4 },
    { text: "a certain deal is closer than anyone realises. {emoji}", vague: 4 },
    { text: "the mask is about to slip. {timeframe}. 🧩", vague: 4 },
    { text: "wait until you find out who was behind it. {emoji}", vague: 4 },

    // --- 5: pure cryptic void, zero information ---
    { text: "if you know, you know.", vague: 5 },
    { text: "well. well well well.", vague: 5 },
    { text: "watch this space 🍿", vague: 5 },
    { text: "you'll understand this tweet in about three weeks.", vague: 5 },
    { text: "not saying anything. just saying. 🤐", vague: 5 },
    { text: "screenshot this one. that's all i ask.", vague: 5 },
    { text: "the people who need to know, already know.", vague: 5 },
    { text: "remember this tweet.", vague: 5 },
    { text: "you can feel it, can't you.", vague: 5 },
    { text: "no.", vague: 5 },
    { text: "hm.", vague: 5 },
    { text: "so it begins. {emoji}", vague: 5 },
    { text: "i tried to warn you.", vague: 5 },
    { text: "it's happening. it's actually happening. {emoji}", vague: 5 },
    { text: "you're not ready. none of you are.", vague: 5 },
    { text: "tick. tock. ⏳", vague: 5 },
    { text: "i'll say this once and never again: {emoji}", vague: 5 },
    { text: "the silence tells you everything.", vague: 5 },
    { text: "read the room. then read it again. {emoji}", vague: 5 },
    { text: "it was never about what you thought it was about.", vague: 5 },
    // ---- expanded batch (mixed levels) ----
    { text: "{driver} to {team}. remember where you heard it. 📌", vague: 1 },
    { text: "{driver} and {team} are closer than anyone realises rn 👀", vague: 1 },
    { text: "don't get too attached to {driver} in that {team} suit. 🤐", vague: 1 },
    { text: "{team} have already made {driver} an offer. that's all i'll say.", vague: 1 },
    { text: "if you think {driver} is staying at {team}, i have a bridge to sell you 🍿", vague: 1 },
    { text: "{driver} to {team2}... sorry, i mean {driver2} to {team}. slip of the thumb. 😏", vague: 1 },
    { text: "{team} know exactly what {driver} is doing {timeframe}. they're not happy.", vague: 1 },
    { text: "watch {driver} very carefully at {gp}. 👀", vague: 1 },
    { text: "{driver} didn't renew with {team} for the reason they told you.", vague: 1 },
    { text: "a big {team} announcement is coming {timeframe}. it involves {driver}. 🤐", vague: 1 },
    { text: "{driver} was spotted somewhere {team} would rather he wasn't. 😏", vague: 1 },
    { text: "the {driver} to {team} deal is done. paperwork later. 📄", vague: 1 },
    { text: "{team} are about to regret letting {driver} walk. mark it. 📌", vague: 1 },
    { text: "{driver2} is not thrilled about the {driver} situation at {team}. 🍿", vague: 1 },
    { text: "remember this post when {driver} shows up at {team} next season. 👀", vague: 1 },
    { text: "{team}'s golden boy isn't {driver} anymore. figure out the rest.", vague: 1 },
    { text: "{driver} and {team} have been quietly talking since {gp}. 🤐", vague: 1 },
    { text: "whatever {team} tells you about {driver} {timeframe}, believe the opposite. 😏", vague: 1 },
    { text: "i've seen the {driver} contract. it does not say {team}. 📌", vague: 1 },
    { text: "{driver} to {team}. not a rumour. not confirming either. 👀", vague: 1 },
    { text: "{team} made a call {timeframe} that changes everything for {driver}.", vague: 1 },
    { text: "screenshot this: {driver} won't finish the season at {team}. 🍿", vague: 1 },
    { text: "{driver} already knows he's leaving {team}. the team doesn't yet. 🤐", vague: 1 },
    { text: "so THAT'S why {driver} was smiling after {gp}. 😏", vague: 2 },
    { text: "there's a reason {team} went quiet {timeframe}. you'll find out. 🤐", vague: 2 },
    { text: "what {driver} said behind closed doors would end careers. 👀", vague: 2 },
    { text: "{team} know. they've known since {gp}. they're just not saying. 🍿", vague: 2 },
    { text: "if only you'd seen {driver}'s face when he heard the news. 😏", vague: 2 },
    { text: "something happened in the {team} garage at {gp} and it wasn't the car. 🤐", vague: 2 },
    { text: "{driver} isn't tired. it's not fatigue. that's the story. 👀", vague: 2 },
    { text: "the real reason {driver} pitted at {gp} has nothing to do with tyres. 🤔", vague: 2 },
    { text: "ask {team} what really happened {timeframe}. they'll change the subject. 😏", vague: 2 },
    { text: "{driver} made a phone call after {gp} that i really wish i could tell you about. 🍿", vague: 2 },
    { text: "you'll understand why {driver} was so calm once it comes out. 🤐", vague: 2 },
    { text: "there's a meeting at {team} {timeframe} that officially isn't happening. 👀", vague: 2 },
    { text: "{driver} didn't lose {gp}. someone made sure of that. 😏", vague: 2 },
    { text: "the thing {team} is hiding since {gp} is bigger than a car upgrade. 🍿", vague: 2 },
    { text: "{driver} knows something about {timeframe} that the paddock doesn't. 🤔", vague: 2 },
    { text: "funny how {team} suddenly cancelled everything after {gp}. 👀", vague: 2 },
    { text: "what {driver} did in that debrief... i still can't believe it. 🤐", vague: 2 },
    { text: "the {gp} result makes a lot more sense once you know what i know. 😏", vague: 2 },
    { text: "{team} aren't panicking about pace. it's something else entirely. 🍿", vague: 2 },
    { text: "the reason {driver} skipped media {timeframe} is not what they claimed. 👀", vague: 2 },
    { text: "one number on {driver}'s dash at {gp} explains everything. 🤔", vague: 2 },
    { text: "you'll remember where you were when the {gp} story finally drops. 🍿", vague: 2 },
    { text: "{team} promised something before {gp} and then didn't deliver. 😏", vague: 2 },
    { text: "there's a photo from {gp} that {team} desperately wants deleted. 🤐", vague: 2 },
    { text: "a certain {nationality} driver just found out. the mood is... {vibe}. 🍿", vague: 3 },
    { text: "two drivers. one team. one very awkward dinner {timeframe}. 😏", vague: 3 },
    { text: "the {vibe} in there right now is unreal and i can't say more 🤐", vague: 3 },
    { text: "a big name is about to blink. that's all you're getting. 👀", vague: 3 },
    { text: "someone's engineer knows and someone's engineer doesn't. 🤔", vague: 3 },
    { text: "there's a {nationality} driver who did NOT take the news well. 🍿", vague: 3 },
    { text: "a garage just went very quiet and it's not for a good reason. 😏", vague: 3 },
    { text: "whatever you think is happening {timeframe}, it's worse. and funnier. 🤐", vague: 3 },
    { text: "a certain someone is packing more than his helmet. 👀", vague: 3 },
    { text: "the vibe went from {vibe} to something else in about ten seconds. 🍿", vague: 3 },
    { text: "a driver you like is lying to you {timeframe}. gently. with a smile. 😏", vague: 3 },
    { text: "the person who leaked it already regrets it. i would know. 🤐", vague: 3 },
    { text: "one paddock. two secrets. same weekend. 👀", vague: 3 },
    { text: "a {nationality} driver just made a decision he can't take back. 🤔", vague: 3 },
    { text: "somebody's about to become a very expensive free agent. 🍿", vague: 3 },
    { text: "the mood in that motorhome {timeframe} was pure {vibe}. 😏", vague: 3 },
    { text: "a certain garage cleared the room. never good. 🤐", vague: 3 },
    { text: "you'll notice one seat looks different {timeframe}. that's the tell. 👀", vague: 3 },
    { text: "a driver's manager has been very busy this week. very. 🤔", vague: 3 },
    { text: "the {vibe} energy in that garage says everything the press release won't. 🍿", vague: 3 },
    { text: "someone just realised they backed the wrong side. 😏", vague: 3 },
    { text: "a certain {nationality} driver stopped smiling {timeframe}. that's the news. 🤐", vague: 3 },
    { text: "certain people are about to have a very bad week {emoji}", vague: 4 },
    { text: "we are NOT ready for what's coming {timeframe}", vague: 4 },
    { text: "some of you are going to feel very silly {timeframe} 👀", vague: 4 },
    { text: "they think we didn't notice. we noticed.", vague: 4 },
    { text: "a decision has been made. that's all i'll say.", vague: 4 },
    { text: "screenshot this. you'll want it later 🤐", vague: 4 },
    { text: "something moved behind the scenes today and nobody's talking about it", vague: 4 },
    { text: "the paperwork is already signed. the rest is theatre.", vague: 4 },
    { text: "a few people in the paddock know exactly what i mean 🫡", vague: 4 },
    { text: "it's not what they announced. it's what they DIDN'T announce.", vague: 4 },
    { text: "there's a reason it went quiet all of a sudden 👀", vague: 4 },
    { text: "the pieces are moving. most of you can't see the board yet 🧩", vague: 4 },
    { text: "a certain someone knows their days are numbered.", vague: 4 },
    { text: "wait until you find out who was in that meeting.", vague: 4 },
    { text: "they'll spin it as a surprise {timeframe}. it isn't.", vague: 4 },
    { text: "someone's about to get very rich and someone's about to get very fired", vague: 4 },
    { text: "i said what i said back in march. reread it.", vague: 4 },
    { text: "the silence from a certain camp is deafening 🤐", vague: 4 },
    { text: "the deal everyone thinks is dead is very much alive {emoji}", vague: 4 },
    { text: "funny how nobody wants to talk about {timeframe} anymore", vague: 4 },
    { text: "there are two people who could stop this. neither one will.", vague: 4 },
    { text: "the announcement isn't the story. the delay is.", vague: 4 },
    { text: "a contract got shorter today and it wasn't the one you think", vague: 4 },
    { text: "keep an eye on who suddenly goes quiet {timeframe} 👀", vague: 4 },
    { text: "one phone call {timeframe} changes all of it", vague: 4 },
    { text: "they're not denying it. read that again.", vague: 4 },
    { text: "the ones panicking right now know exactly why 🍿", vague: 4 },
    { text: "something's cooking and the smell reached the paddock {timeframe}", vague: 4 },
    { text: "a handshake happened that was never supposed to happen", vague: 4 },
    { text: "the real news broke {timeframe}. you just didn't hear it yet.", vague: 4 },
    { text: "certain garages are a lot more nervous than they're letting on", vague: 4 },
    { text: "nobody's ready for the second half of this story ⏳", vague: 4 },
    { text: "👀", vague: 5 },
    { text: "interesting. very interesting.", vague: 5 },
    { text: "oh?", vague: 5 },
    { text: "i knew it 🍿", vague: 5 },
    { text: "so it begins.", vague: 5 },
    { text: "told you.", vague: 5 },
    { text: "noted. 🤐", vague: 5 },
    { text: "soon {emoji}", vague: 5 },
    { text: "you didn't hear it from me.", vague: 5 },
    { text: "just wait.", vague: 5 },
    { text: "as i suspected 🫡", vague: 5 },
    { text: "can't say. but wow.", vague: 5 },
    { text: "the bit i can't tweet is even better", vague: 5 },
    { text: "...and there it is.", vague: 5 },
    { text: "i'm going to pretend i didn't see that 👀", vague: 5 },
    { text: "okay okay okay okay", vague: 5 },
    { text: "screenshotted. moving on.", vague: 5 },
    { text: "no comment 🤐", vague: 5 },
    { text: "we don't say his name yet.", vague: 5 },
    { text: "my phone won't stop buzzing and no i won't explain", vague: 5 },
    { text: "putting the phone down before i say too much", vague: 5 },
    { text: "ha.", vague: 5 },
    { text: "you'll get it later ⏳", vague: 5 },
    { text: "deleting this in an hour.", vague: 5 },
    { text: "NOT touching this one. yet.", vague: 5 },
    { text: "good morning to the three people who understand this tweet", vague: 5 },
    { text: "i've said too much already 🤐", vague: 5 },
    { text: "anyway. 👀", vague: 5 },
    { text: "the group chat is UNWELL right now 🍿", vague: 5 },
    { text: "believe me later.", vague: 5 },
    { text: "tick tock ⏳", vague: 5 },
    { text: "you're not ready. i'm not either.", vague: 5 }
  ]
};
